language: node_js

node_js:
    - "8"
    - "9"
    - "10"

services:
    - mongodb

branches:
  only:
    - master

cache:
    yarn: true
    directories:
        - node_modules

jobs:
  include:
    - stage: build
    - script: yarn build
    - stage: test
    - script: yarn test